### ISSUE TITLE
fonipa font

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#1]
We're using `mui-language-picker` in https://github.com/sillsdev/TheCombine and one of our users has suggested that for ~~language "Japanese (ja-fonipa)"~~_any language_ and script "Phonetic - fonipa", the default font should be "DoulosSIL" instead of ~~"Noto Sans CJK JP"~~_the default for that language_.

<img width="602" alt="Screen Shot 2021-01-29 at 17 19 44" src="https://user-images.githubusercontent.com/6411521/106333322-666c1180-6256-11eb-8502-59be15cf1616.png">

**Comment by gtryus** [comment]
ok, thank you for the suggestion. I think it is a good idea. Let me look
into how difficult that might be. Is the issue that There is not other font
option or that the default option isn't the best?

Greg Trihus
Skype: gtryus / Facebook <http://www.facebook.com/gtrihus> / LinkedIn
<http://www.linkedin.com/pub/greg-trihus/15/602/335>

**Comment by imnasnainaec** [comment]
When a user selections language "Japanese (ja)", the default script is "Japanese (alias for Han + Hiragana + Katakana) - ..." and the two font options are "Noto Sans CJK JP" and "Noto Serif CJK JP". If the user changes script to "Phonetic - fonipa", the language code updates from (ja) to (ja-fonipa), but the font options do not change.

**Comment by gtryus** [comment]
Thanks, I'll check it out.
Greg Trihus
Skype: gtryus / Facebook <http://www.facebook.com/gtrihus> / LinkedIn
<http://www.linkedin.com/pub/greg-trihus/15/602/335>

**Comment by imnasnainaec** [comment]
I just realized that fonipa is IPA, not Japanese specific, so I edited the original text of this issue accordingly.

**Comment by gtryus** [comment]
I updated the language picker to address this issue.

Greg Trihus
Skype: gtryus / Facebook <http://www.facebook.com/gtrihus> / LinkedIn
<http://www.linkedin.com/pub/greg-trihus/15/602/335>

**Comment by imnasnainaec** [comment]
https://github.com/sillsdev/mui-language-picker/commit/5ce774e5d62af50111b742272d26c7c53abd2ea4
Thanks!

**Comment by imnasnainaec** [comment]
@gtryus There's still odd behavior in one case:
When switching "Script" from "Phonetic (IPA) - fonipa" back to the language's default, the font options don't update.

**Comment by gtryus** [comment]
Yes it is in the nature of keeping the interaction as simple as possible.
The default case is "unmarked" and once you have marked it,  the preference
is toward retaining the marked case. Of course the user can always click
the X and type the code again. Language codes allow a lot of markup that
the user can't select from menu options and doesn't necessarily want to
lose when they pick another option.

**Comment by gtryus** [comment]
If you have a pull request suggestion, I'll look it over. Otherwise, I am
working on a release today and will have to get to it a bit later.

Greg Trihus

**Comment by imnasnainaec** [comment]
@gtryus I tried this again, and I don't understand the behavior. I start with language "Japanese (ja)".
* If I select script "Latin - Ltn", the language updates to "Japanese (ja-Ltn)" and the font options change; then when I select the default script "Japanese (alias for Han + Hiragana + Katakana) - ...", the language reverts to "Japanese (ja)" and the font options also revert.
* If I select script "Phonetic (IPA) - fonipa", the language changes to "Japanese (ja-fonipa)" and the fonts update; but when I select the default script, the language and fonts *do not* revert.
By your description, I would have expected it not to revert in any situation, but it is only "-fonipa" that prevents reverting to the "unmarked" state.
