### ISSUE TITLE
scripts.csv, langtags.json out of date

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#11]
https://github.com/sillsdev/mui-language-picker/blob/master/src/data/scripts.csv is out of sync with https://github.com/silnrsi/langfontfinder/blob/main/data/script2font.csv (which I assume is its source).

**Comment by imnasnainaec** [comment]
Similarly https://github.com/sillsdev/mui-language-picker/blob/master/src/data/langtags.json and https://github.com/silnrsi/langtags/tree/master/source.

**Comment by gtryus** [comment]
These have been updated using the language font family (lff) api

**Comment by imnasnainaec** [comment]
@gtryus It looks like https://github.com/sillsdev/mui-language-picker/blob/master/src/data/scripts.csv is still the old data.
