### ISSUE TITLE
Question on searching for languages by their localized name

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#12]
Not so much an issue, but a question from an Arabic user of The Combine:

> Is it possible to search for languages by their localized name (e.g., "العربية" instead of "Arabic")?
> Or is there a plan to make that available?

**Comment by gtryus** [comment]
yes, I would like to make that available but I am not sure it is there
yet...

**Comment by gtryus** [comment]
This is now possible with version 2.0
