### ISSUE TITLE
Script and Font dropdown menus overflow the box in a narrow window

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#17]
At around < 450px wide, the Script dropdown menu is wider than its container and overflows on the right rather than shrinking:
![Screenshot 2024-04-19 100233](https://github.com/sillsdev/mui-language-picker/assets/6411521/44fbfb2c-820c-4641-9756-77e76a3e170c)

Similarly, at around < 325px, the Font dropdown menu starts to overflow:
![Screenshot 2024-04-19 100354](https://github.com/sillsdev/mui-language-picker/assets/6411521/fed59781-fb37-4768-aa32-9cf18bc92565)

Then at around < 250px, the Code Explainer link starts to run off the left side:
![Screenshot 2024-04-19 100621](https://github.com/sillsdev/mui-language-picker/assets/6411521/d16c8e8b-3df6-4a93-8a21-f220bc1ab330)

The top issue of these three is especially prevalent on mobile devices.

**Comment by gtryus** [comment]
I think it also depends on how you set the browser zoom option.

**Comment by gtryus** [comment]
We could also create a mobile support version with @media queries for different sized screens.

**Comment by imnasnainaec** [comment]
#20 would be one way about it, to just have the width of the two dropdown menus change with the width of the dialog.

**Comment by imnasnainaec** [comment]
(But you should test that yourself to see if you like it.)

**Comment by gtryus** [comment]
Would it make sense to use maxWidth instead of width which would allow the controls to be smaller but not larger?

**Comment by imnasnainaec** [comment]
You could try that out too, but I think the whole control shrinks awkwardly small if no content forces it wider.

**Comment by gtryus** [comment]
I am guessing the demo might look pretty funny with 100% too since it is the only control on the page when the demo opens ... it would be the full width of the screen.

**Comment by imnasnainaec** [comment]
This change shouldn't affect the dialog width, just expand the controls within the dialog.

**Comment by gtryus** [comment]
Yes, I am trying it and see what you mean.
