### ISSUE TITLE
Unexpected case sensitivity in the language search results

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#18]
When I type "es-CO" there are two results: first "es-CO" and second "es". This makes sense to me.
When I type "es-Co" or "es-co" there is only one result: "es".

Similarly, if I type "en", then English ("en") is the first result.
However, "En" only gives En ("enc") as the second result and English ("en") as the 7th result, which I have to scroll to find.

**Comment by gtryus** [comment]
The comment is interesting although I think the bcp-47 standard is specific on the cases to be used for language identifiers and country codes. So in fact, I think the program is working according to the standard.

**Comment by imnasnainaec** [comment]
Now when I try "En" in the demo (http://mui-language-picker-demo.org.s3-website-us-east-1.amazonaws.com/), I have to scroll a very long time to get past the "English"es and find "En (enc)".

**Comment by DavidLRowe** [comment]
By convention, the different subtags of a language tag are formatted differently (language in lowercase, script in Title case, region in CAPS, etc.), however, the case difference doesn't change the meaning. "In [[BCP47](https://w3c.github.io/ltli/#bib-bcp47)], subtags can consist of upper or lowercase ASCII letters (the case carries no distinction) or ASCII digits." [Language Tags and Locale Identifiers for the World Wide Web](https://w3c.github.io/ltli/)

I don't know if that makes a difference to the logic of the program. If a user enters "En" should you give preference to language names over language codes?

**Comment by gtryus** [comment]
I added a change that puts the canonical name at the beginning of the list of matches.

**Comment by imnasnainaec** [comment]
For reference: https://github.com/sillsdev/mui-language-picker/commit/106d5ac403d84c7aafc8af8657ae58b00385687f
