### ISSUE TITLE
No font options available for Braille (-Brai)

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#19]
Many major languages have a -Brai script option for Braille; selecting this results in an empty font list.

**Comment by imnasnainaec** [comment]
Perhaps the safe fonts could be a fallback when no fonts are offered.

**Comment by imnasnainaec** [comment]
I'm giving feedback there when I find good options:

- https://github.com/silnrsi/langfontfinder/issues/13
- https://github.com/silnrsi/langfontfinder/pull/14

I was wondering if the you'd want a fallback when the api gives no options. And if not, that's perfectly find---you can close this issue.

**Comment by gtryus** [comment]
If there are no recommended fonts, should we hid the font choice control? Should we not call setFont call back if there is no font?

**Comment by imnasnainaec** [comment]
Hmm, good questions.

I'm guessing a disabled dropdown with some "No recommended fonts" text would be less confusing than having the whole control disappear.

I don't immediately see any harm in letting `setFont` be called with an empty string, but I've not thought of a good use case that would decide it one way or the other.

**Comment by gtryus** [comment]
I like the idea of calling setFont anyway (at least) since if the user picked a language with a font and are now editing their choice, you don't want the old font to be retained.

Disabled controls are tricky since there is no easy way to make the "No recommended fonts" message appear... (Titles and hovering is also disabled when the control is disabled.)

**Comment by gtryus** [comment]
I could put a little information (i) after the control if it is disabled with the text on that. Does that sound like a good idea?

**Comment by imnasnainaec** [comment]
You could have the `select` prop in https://github.com/sillsdev/mui-language-picker/blob/master/src/LanguagePicker.tsx#L512 conditional on whether `fontOpts` is empty.

**Comment by gtryus** [comment]
ok, I made this change and merged to master branch.

**Comment by imnasnainaec** [comment]
https://github.com/sillsdev/mui-language-picker/commit/5a41dd52770d1c309e51ef48689f237816cc436e looks good
