### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by strarsis** [sillsdev/mui-language-picker#3]
Please add a demo and a link to it on the README!

**Comment by AlanBlanchet** [comment]
Would also like a demo. You could also add an image to introduce this package

**Comment by gtryus** [comment]
I added a demo video and a demo app for your review.

**Comment by gtryus** [comment]
There is a demo project which can also be used for debugging purposes. by creating a folder called mui-language-picker and copying the src folder from the picker into it.
