### ISSUE TITLE
When fonipa script selected, LangTag uses default script instead

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#4]
On any language, select the IPA script (fonipa) and click SAVE. The `LangTag` used for `setInfo` has the language's default for `Script` instead of fonipa. Moreover, clicking on the language picker to alter the selection has the script dropdown menu back on the default instead of on IPA.

Edit: "fonipa" is available under `.variant` instead of `.script`.

**Comment by gtryus** [comment]
This now works correctly in the program with version 2.0

**Comment by imnasnainaec** [comment]
@gtryus I think this is still an issue, and may be related to #14

**Comment by imnasnainaec** [comment]
I think this was resolved in 2.1.2.
